name: CI CD Docker Build and Push

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: mid-program-project-demo
  HF_SPACE_REPO_URL: https://huggingface.co/spaces/nachikethmurthy666/mid-project-project

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
          lfs: true      # Checkout LFS files

      - name: Get Commit hash
        id: vars
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image with commit hash
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.GIT_SHA }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest .

      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.GIT_SHA }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Install Git LFS and Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Ensure git-lfs is installed (GitHub runners usually have it, but good practice)
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install --system # Initialize LFS for the system

          # The 'actions/checkout' step above has already cloned your repository
          # and fetched LFS files because of `lfs: true` and `Workspace-depth: 0`.

          # Set up user for potential commits if needed (though direct push might not require a new commit)
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          
          echo "Setting remote for Hugging Face Space"
          # Add the Hugging Face Space as a remote.
          # The URL uses oauth2 for token-based authentication.
          git remote add huggingface https://oauth2:${HF_TOKEN}@${HF_SPACE_REPO_URL#https://}
          
          echo "Pushing to Hugging Face Space: ${{ env.HF_SPACE_REPO_URL }}"
          # Push the main branch to the Hugging Face Space.
          # --force is used to overwrite the history on the Space, ensuring it matches your GitHub repo.
          # This should resolve the "shallow update not allowed" because the local repo now has full history.
          # LFS files will be pushed automatically.
          git push --force huggingface main
          
          echo "Successfully pushed to Hugging Face Space"